version: '3'

services:
  # Сервис API (backend)
  api:
    restart: always
    container_name: api
    build: ./api  
    ports:
      - "5555:5000"  
    depends_on:
      - mysql  

  # Сервис Frontend
  frontend:
    restart: always
    container_name: frontend
    build: ./frontend  
    ports:
      - "8954:8954"  
    depends_on:
      - api  

  # Сервис MySQL
  mysql:
    restart: always
    container_name: mysql
    image: mysql 
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql  

  # Сервис Adminer (для администрирования базы данных)
  adminer:
    restart: always
    container_name: adminer
    image: adminer
    ports:
      - "8795:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
